### ISSUE TITLE
Repeated fml's create excess panes

### ISSUE THREAD

**Issue by SnoringFrog** [ktonga/vim-follow-my-lead#10]
If you do `<leader>fml` multiple times in a row, you can multiple `fml` panes. Unless I'm missing something, I can't think of any reason someone would want/need multiple panes. Maybe it's worth looking into making a second `fml` just refresh the old pane (or close it an open a new one, either way).

This might not be a trivial change, and it only fixes a minor annoyance, so it's more of a "if this happens to be convenient it'd be nice" than a bug/issue. 

(Sidenote: sorry for all the issues I'm posting, I do really enjoy this plugin though)

**Comment by ktonga** [comment]
Updating when invoking and window is already open is a great idea. I will implement it.

Thank you for reporting. I enjoy you enjoy this plugin ☺
