### ISSUE TITLE
Invoking fml twice in succession doesn't work

### ISSUE THREAD

**Issue by pmcRTR** [ktonga/vim-follow-my-lead#12]
Tested on latest Vim v7.4.898 running on Ubuntu Linux 15.04

Open Vim
Run <code><leader>fml</code>
Expected behaviour occurs (new split opens showing leader mappings and entering q closes the split)
Immediately on closing the fml split, run <code><leader>fml</code> again
This time the leader mappings appear directly in the current buffer and q does not close

**Comment by ktonga** [comment]
Ohh, that's so dangerous. Thank you for reporting! I'll take a look at it ASAP.

Sorry about the delay, somehow I've unsubscribed from my own repositories notifications so I just saw it.
